# Generated by Django 5.2.3 on 2025-06-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("railway", "0002_alter_train_cargo_num_alter_train_places_in_cargo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="traintype",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
