# Generated by Django 5.2.3 on 2025-06-29 09:11

import railway.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("railway", "0003_alter_traintype_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="train",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=railway.models.train_image_path
            ),
        ),
    ]
